version: '3.2'

volumes:
  rabbit-data:
  composer-data:

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - composer-data:/tmp/composer:cached
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      PS1: '\[\033[1;32m\]\[\033[1;36m\][\u@docker] \[\033[1;34m\]\w\[\033[0;35m\] \[\033[1;36m\]# \[\033[0m\]'
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: '/'
    volumes:
      - rabbit-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit:cached
    ports:
      - 5672
     #- '8081:15672' # web face
    networks:
      - app-network
